name: employee-directory

services:
  postgres:
    image: postgres:16-alpine
    container_name: employee-directory-db
    environment:
      POSTGRES_DB: EmployeeDirectory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "7777:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: employeedirectory:dev
    container_name: employee-directory-web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=EmployeeDirectory;Username=postgres;Password=root
      - TZ=Europe/Moscow
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

